# This file contains the following steps:
#
#
#
#

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Simple repo tesing

jobs:

  Linting:
    runs-on: ["self-hosted", "m92p"]
    name: Linting
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.1' 

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH=/home/docker/.local/bin:$PATH
        poetry --version
        poetry update

    - name: Install dependencies with Poetry
      run: |
        poetry install --no-interaction

    - name: Run Pylint
      run: |
        pylint src/

#    - name: Run Pylint
#      uses: davidslusser/actions_python_pylint@v1.0.0
#      with:
#        src: "src"
#        python_version: "3.12.1"
