#
# Pipeline v1.0 (2024-02-05)
#
# Poetry export to Pip
# poetry export --without-hashes --without dev -f requirements.txt -o requirements.txt
#

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Simple repo testing

jobs:

  Stage1:
    runs-on: ["self-hosted", "m92p"]
    name: Linting
    steps:

    # This step checkout code into local container
    - name: Checkout code
      uses: actions/checkout@v4

    # This step configures python into the path
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.1'

    # This step install project dependencies from pip requirements file
    - uses: insightsengineering/pip-action@v2
      with:
        requirements: requirements.txt

    # This step perform a pylint exec over code
    - name: Run Pylint
      uses: davidslusser/actions_python_pylint@v1.0.0
      with:
        src: "src"
        python_version: "3.12.1"
