# This file contains the following steps:
#
#
#
#

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Simple repo tesing

jobs:

  Stage1:
    # runs-on: ["self-hosted", "m92p"]
    runs-on: ubuntu-latest
    name: Linting
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1' 

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry --version
        poetry update

    - name: Install dependencies with Poetry
      run: |
        poetry install  --no-root --no-interaction

    - name: Run Pylint
      uses: davidslusser/actions_python_pylint@v1.0.0
      with:
        src: "src"
        python_version: "3.12.1"
